services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8088:8088"
  #   networks:
  #     mynetwork:
  #       ipv4_address: 172.10.0.2
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5444/db?sslmode=disable
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      mynetwork:
        ipv4_address: 172.10.0.3
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/16
